import { Player } from './types';

const chronicleBaseUrl = 'https://raw.githubusercontent.com/niwde787/basketball-legends/refs/heads/chronicles/';
const playerImgBaseUrl = 'https://raw.githubusercontent.com/niwde787/basketball-legends/refs/heads/players/';

export const POSITIONS = ["PG", "SG", "SF", "PF", "C"];

export const players: { [key: string]: Player } = {
    // GOAT Tier
    "lebron_james": { id: 1, name: "LeBron James", pos: "SF", tier: "GOAT", attributes: { inside_scoring: 98, mid_range: 85, three_point: 82, playmaking: 99, perimeter_defense: 90, interior_defense: 80, rebounding: 85, athleticism: 97, basketball_iq: 100 }, career_stats: { usg_pct: 31.5, fg_pct: 50.5, ppg: 27.1, rpg: 7.5, apg: 7.4 }, shot_tendencies: { inside: 55, mid: 20, three: 25 }, target_minutes: 38, traits: ["Floor General", "Transition Threat", "Alpha Dog"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id1.webp`, chronicle_img_url: `${chronicleBaseUrl}id1.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "michael_jordan": { id: 2, name: "Michael Jordan", pos: "SG", tier: "GOAT", attributes: { inside_scoring: 98, mid_range: 100, three_point: 75, playmaking: 90, perimeter_defense: 98, interior_defense: 70, rebounding: 75, athleticism: 98, basketball_iq: 97 }, career_stats: { usg_pct: 33.3, fg_pct: 49.7, ppg: 30.1, rpg: 6.2, apg: 5.3 }, shot_tendencies: { inside: 45, mid: 50, three: 5 }, target_minutes: 38, traits: ["Clutch Performer", "Alpha Dog", "Unstoppable Scorer"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id2.webp`, chronicle_img_url: `${chronicleBaseUrl}id2.webp`, era: "Modern Era (1990s-2000s)" },
    "kareem_abdul_jabbar": { id: 3, name: "Kareem Abdul-Jabbar", pos: "C", tier: "GOAT", attributes: { inside_scoring: 100, mid_range: 88, three_point: 10, playmaking: 78, perimeter_defense: 60, interior_defense: 96, rebounding: 94, athleticism: 88, basketball_iq: 98 }, career_stats: { usg_pct: 28.5, fg_pct: 55.9, ppg: 24.6, rpg: 11.2, apg: 3.6 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 38, traits: ["Unstoppable Scorer", "Rim Protector"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id3.webp`, chronicle_img_url: `${chronicleBaseUrl}id3.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "magic_johnson": { id: 4, name: "Magic Johnson", pos: "PG", tier: "GOAT", attributes: { inside_scoring: 92, mid_range: 80, three_point: 70, playmaking: 100, perimeter_defense: 80, interior_defense: 60, rebounding: 80, athleticism: 88, basketball_iq: 99 }, career_stats: { usg_pct: 22.8, fg_pct: 52.0, ppg: 19.5, rpg: 7.2, apg: 11.2 }, shot_tendencies: { inside: 60, mid: 30, three: 10 }, target_minutes: 37, traits: ["Floor General", "Transition Threat"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id4.webp`, chronicle_img_url: `${chronicleBaseUrl}id4.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "larry_bird": { id: 5, name: "Larry Bird", pos: "SF", tier: "GOAT", attributes: { inside_scoring: 88, mid_range: 96, three_point: 90, playmaking: 94, perimeter_defense: 80, interior_defense: 72, rebounding: 88, athleticism: 80, basketball_iq: 100 }, career_stats: { usg_pct: 26.5, fg_pct: 49.6, ppg: 24.3, rpg: 10.0, apg: 6.3 }, shot_tendencies: { inside: 35, mid: 45, three: 20 }, target_minutes: 38, traits: ["Clutch Performer", "Floor General"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id5.webp`, chronicle_img_url: `${chronicleBaseUrl}id5.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "wilt_chamberlain": { id: 6, name: "Wilt Chamberlain", pos: "C", tier: "GOAT", attributes: { inside_scoring: 100, mid_range: 75, three_point: 5, playmaking: 70, perimeter_defense: 50, interior_defense: 95, rebounding: 100, athleticism: 100, basketball_iq: 85 }, career_stats: { usg_pct: 30.0, fg_pct: 54.0, ppg: 30.1, rpg: 22.9, apg: 4.4 }, shot_tendencies: { inside: 90, mid: 10, three: 0 }, target_minutes: 40, traits: ["Post Anchor", "Tireless Motor"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id6.webp`, chronicle_img_url: `${chronicleBaseUrl}id6.webp`, era: "Pioneers Era (1940s-1960s)" },
    "bill_russell": { id: 7, name: "Bill Russell", pos: "C", tier: "GOAT", attributes: { inside_scoring: 75, mid_range: 50, three_point: 5, playmaking: 75, perimeter_defense: 70, interior_defense: 100, rebounding: 99, athleticism: 90, basketball_iq: 100 }, career_stats: { usg_pct: 16.6, fg_pct: 44.0, ppg: 15.1, rpg: 22.5, apg: 4.3 }, shot_tendencies: { inside: 95, mid: 5, three: 0 }, target_minutes: 36, traits: ["Rim Protector", "Alpha Dog"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id7.webp`, chronicle_img_url: `${chronicleBaseUrl}id7.webp`, era: "Pioneers Era (1940s-1960s)" },
    "kobe_bryant": { id: 8, name: "Kobe Bryant", pos: "SG", tier: "GOAT", attributes: { inside_scoring: 95, mid_range: 98, three_point: 85, playmaking: 86, perimeter_defense: 94, interior_defense: 65, rebounding: 70, athleticism: 95, basketball_iq: 96 }, career_stats: { usg_pct: 31.8, fg_pct: 44.7, ppg: 25.0, rpg: 5.2, apg: 4.7 }, shot_tendencies: { inside: 35, mid: 45, three: 20 }, target_minutes: 37, traits: ["Clutch Performer", "Alpha Dog", "Unstoppable Scorer"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id8.webp`, chronicle_img_url: `${chronicleBaseUrl}id8.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "tim_duncan": { id: 9, name: "Tim Duncan", pos: "PF", tier: "GOAT", attributes: { inside_scoring: 96, mid_range: 90, three_point: 30, playmaking: 78, perimeter_defense: 75, interior_defense: 98, rebounding: 95, athleticism: 85, basketball_iq: 98 }, career_stats: { usg_pct: 27.0, fg_pct: 50.6, ppg: 19.0, rpg: 10.8, apg: 3.0 }, shot_tendencies: { inside: 75, mid: 25, three: 0 }, target_minutes: 36, traits: ["Post Anchor", "Rim Protector", "Floor General"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id9.webp`, chronicle_img_url: `${chronicleBaseUrl}id9.webp`, era: "Modern Era (1990s-2000s)" },
    
    // Legend Tier
    "stephen_curry": { id: 10, name: "Stephen Curry", pos: "PG", tier: "Legend", attributes: { inside_scoring: 88, mid_range: 92, three_point: 100, playmaking: 92, perimeter_defense: 80, interior_defense: 40, rebounding: 65, athleticism: 88, basketball_iq: 95 }, career_stats: { usg_pct: 29.0, fg_pct: 47.3, ppg: 24.6, rpg: 4.7, apg: 6.5 }, shot_tendencies: { inside: 25, mid: 25, three: 50 }, target_minutes: 35, traits: ["Heat Check", "Floor General", "Unstoppable Scorer"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id10.webp`, chronicle_img_url: `${chronicleBaseUrl}id10.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "kevin_durant": { id: 11, name: "Kevin Durant", pos: "SF", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 99, three_point: 92, playmaking: 85, perimeter_defense: 85, interior_defense: 80, rebounding: 80, athleticism: 90, basketball_iq: 94 }, career_stats: { usg_pct: 30.3, fg_pct: 49.3, ppg: 27.2, rpg: 7.1, apg: 4.2 }, shot_tendencies: { inside: 30, mid: 40, three: 30 }, target_minutes: 37, traits: ["Unstoppable Scorer", "Heat Check", "Clutch Performer"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id11.webp`, chronicle_img_url: `${chronicleBaseUrl}id11.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "hakeem_olajuwon": { id: 12, name: "Hakeem Olajuwon", pos: "C", tier: "Legend", attributes: { inside_scoring: 97, mid_range: 85, three_point: 20, playmaking: 70, perimeter_defense: 75, interior_defense: 99, rebounding: 93, athleticism: 92, basketball_iq: 95 }, career_stats: { usg_pct: 28.9, fg_pct: 51.2, ppg: 21.8, rpg: 11.1, apg: 2.5 }, shot_tendencies: { inside: 75, mid: 25, three: 0 }, target_minutes: 36, traits: ["Unstoppable Scorer", "Rim Protector"], foul_tendency: 8, img_url: `${playerImgBaseUrl}id12.webp`, chronicle_img_url: `${chronicleBaseUrl}id12.webp`, era: "Modern Era (1990s-2000s)" },
    "shaquille_oneal": { id: 13, name: "Shaquille O'Neal", pos: "C", tier: "Legend", attributes: { inside_scoring: 100, mid_range: 25, three_point: 5, playmaking: 65, perimeter_defense: 30, interior_defense: 92, rebounding: 94, athleticism: 95, basketball_iq: 80 }, career_stats: { usg_pct: 29.5, fg_pct: 58.2, ppg: 23.7, rpg: 10.9, apg: 2.5 }, shot_tendencies: { inside: 99, mid: 1, three: 0 }, target_minutes: 35, traits: ["Post Anchor", "Rim Protector"], foul_tendency: 9, img_url: `${playerImgBaseUrl}id13.webp`, chronicle_img_url: `${chronicleBaseUrl}id13.webp`, era: "Modern Era (1990s-2000s)" },
    "oscar_robertson": { id: 14, name: "Oscar Robertson", pos: "PG", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 92, three_point: 50, playmaking: 98, perimeter_defense: 85, interior_defense: 60, rebounding: 82, athleticism: 85, basketball_iq: 96 }, career_stats: { usg_pct: 26.0, fg_pct: 48.5, ppg: 25.7, rpg: 7.5, apg: 9.5 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 38, traits: ["Floor General", "Tireless Motor"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id14.webp`, chronicle_img_url: `${chronicleBaseUrl}id14.webp`, era: "Pioneers Era (1940s-1960s)" },
    "dirk_nowitzki": { id: 15, name: "Dirk Nowitzki", pos: "PF", tier: "Legend", attributes: { inside_scoring: 85, mid_range: 98, three_point: 88, playmaking: 75, perimeter_defense: 60, interior_defense: 70, rebounding: 85, athleticism: 78, basketball_iq: 95 }, career_stats: { usg_pct: 28.0, fg_pct: 47.1, ppg: 20.7, rpg: 7.5, apg: 2.4 }, shot_tendencies: { inside: 25, mid: 50, three: 25 }, target_minutes: 34, traits: ["Unstoppable Scorer", "Clutch Performer"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id15.webp`, chronicle_img_url: `${chronicleBaseUrl}id15.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "kevin_garnett": { id: 16, name: "Kevin Garnett", pos: "PF", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 94, three_point: 60, playmaking: 82, perimeter_defense: 95, interior_defense: 94, rebounding: 92, athleticism: 90, basketball_iq: 93 }, career_stats: { usg_pct: 26.3, fg_pct: 49.7, ppg: 17.8, rpg: 10.0, apg: 3.7 }, shot_tendencies: { inside: 40, mid: 55, three: 5 }, target_minutes: 36, traits: ["Alpha Dog", "Rim Protector", "Tireless Motor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id16.webp`, chronicle_img_url: `${chronicleBaseUrl}id16.webp`, era: "Modern Era (1990s-2000s)" },
    "karl_malone": { id: 17, name: "Karl Malone", pos: "PF", tier: "Legend", attributes: { inside_scoring: 95, mid_range: 88, three_point: 40, playmaking: 70, perimeter_defense: 78, interior_defense: 75, rebounding: 90, athleticism: 94, basketball_iq: 85 }, career_stats: { usg_pct: 28.7, fg_pct: 51.6, ppg: 25.0, rpg: 10.1, apg: 3.6 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 37, traits: ["Post Anchor", "Transition Threat"], foul_tendency: 8, img_url: `${playerImgBaseUrl}id17.webp`, chronicle_img_url: `${chronicleBaseUrl}id17.webp`, era: "Modern Era (1990s-2000s)" },
    "julius_erving": { id: 18, name: "Julius Erving", pos: "SF", tier: "Legend", attributes: { inside_scoring: 97, mid_range: 80, three_point: 65, playmaking: 80, perimeter_defense: 85, interior_defense: 75, rebounding: 85, athleticism: 96, basketball_iq: 90 }, career_stats: { usg_pct: 28.8, fg_pct: 50.6, ppg: 24.2, rpg: 8.5, apg: 4.2 }, shot_tendencies: { inside: 70, mid: 25, three: 5 }, target_minutes: 36, traits: ["Transition Threat", "Unstoppable Scorer"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id18.webp`, chronicle_img_url: `${chronicleBaseUrl}id18.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "moses_malone": { id: 19, name: "Moses Malone", pos: "C", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 70, three_point: 20, playmaking: 60, perimeter_defense: 60, interior_defense: 88, rebounding: 98, athleticism: 85, basketball_iq: 88 }, career_stats: { usg_pct: 26.1, fg_pct: 49.1, ppg: 20.6, rpg: 12.2, apg: 1.4 }, shot_tendencies: { inside: 85, mid: 15, three: 0 }, target_minutes: 34, traits: ["Post Anchor", "Tireless Motor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id19.webp`, chronicle_img_url: `${chronicleBaseUrl}id19.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "jerry_west": { id: 20, name: "Jerry West", pos: "SG", tier: "Legend", attributes: { inside_scoring: 85, mid_range: 95, three_point: 80, playmaking: 90, perimeter_defense: 92, interior_defense: 60, rebounding: 70, athleticism: 88, basketball_iq: 94 }, career_stats: { usg_pct: 30.0, fg_pct: 47.4, ppg: 27.0, rpg: 5.8, apg: 6.7 }, shot_tendencies: { inside: 40, mid: 60, three: 0 }, target_minutes: 37, traits: ["Clutch Performer", "Unstoppable Scorer"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id20.webp`, chronicle_img_url: `${chronicleBaseUrl}id20.webp`, era: "Pioneers Era (1940s-1960s)" },
    "elgin_baylor": { id: 21, name: "Elgin Baylor", pos: "SF", tier: "Legend", attributes: { inside_scoring: 96, mid_range: 90, three_point: 40, playmaking: 80, perimeter_defense: 78, interior_defense: 65, rebounding: 92, athleticism: 93, basketball_iq: 90 }, career_stats: { usg_pct: 29.0, fg_pct: 43.1, ppg: 27.4, rpg: 13.5, apg: 4.3 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 36, traits: ["Unstoppable Scorer", "Tireless Motor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id21.webp`, chronicle_img_url: `${chronicleBaseUrl}id21.webp`, era: "Pioneers Era (1940s-1960s)" },
    "dwyane_wade": { id: 22, name: "Dwyane Wade", pos: "SG", tier: "Legend", attributes: { inside_scoring: 96, mid_range: 84, three_point: 75, playmaking: 88, perimeter_defense: 90, interior_defense: 75, rebounding: 68, athleticism: 94, basketball_iq: 92 }, career_stats: { usg_pct: 32.0, fg_pct: 48.0, ppg: 22.0, rpg: 4.7, apg: 5.4 }, shot_tendencies: { inside: 55, mid: 35, three: 10 }, target_minutes: 35, traits: ["Clutch Performer", "Transition Threat", "Ankle Breaker"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id22.webp`, chronicle_img_url: `${chronicleBaseUrl}id22.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "giannis_antetokounmpo": { id: 23, name: "Giannis Antetokounmpo", pos: "PF", tier: "Legend", attributes: { inside_scoring: 99, mid_range: 72, three_point: 70, playmaking: 85, perimeter_defense: 92, interior_defense: 90, rebounding: 93, athleticism: 100, basketball_iq: 90 }, career_stats: { usg_pct: 32.5, fg_pct: 53.5, ppg: 22.6, rpg: 9.6, apg: 4.7 }, shot_tendencies: { inside: 75, mid: 15, three: 10 }, target_minutes: 34, traits: ["Transition Threat", "Unstoppable Scorer", "Rim Protector"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id23.webp`, chronicle_img_url: `${chronicleBaseUrl}id23.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "scottie_pippen": { id: 24, name: "Scottie Pippen", pos: "SF", tier: "Legend", attributes: { inside_scoring: 85, mid_range: 82, three_point: 75, playmaking: 88, perimeter_defense: 100, interior_defense: 80, rebounding: 80, athleticism: 92, basketball_iq: 93 }, career_stats: { usg_pct: 21.0, fg_pct: 47.3, ppg: 16.1, rpg: 6.4, apg: 5.2 }, shot_tendencies: { inside: 45, mid: 35, three: 20 }, target_minutes: 35, traits: ["Lockdown Defender", "Transition Threat"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id24.webp`, chronicle_img_url: `${chronicleBaseUrl}id24.webp`, era: "Modern Era (1990s-2000s)" },
    "charles_barkley": { id: 25, name: "Charles Barkley", pos: "PF", tier: "Legend", attributes: { inside_scoring: 92, mid_range: 80, three_point: 70, playmaking: 75, perimeter_defense: 70, interior_defense: 65, rebounding: 95, athleticism: 90, basketball_iq: 87 }, career_stats: { usg_pct: 26.6, fg_pct: 54.1, ppg: 22.1, rpg: 11.7, apg: 3.9 }, shot_tendencies: { inside: 65, mid: 25, three: 10 }, target_minutes: 35, traits: ["Tireless Motor", "Post Anchor"], foul_tendency: 8, img_url: `${playerImgBaseUrl}id25.webp`, chronicle_img_url: `${chronicleBaseUrl}id25.webp`, era: "Modern Era (1990s-2000s)" },
    "john_stockton": { id: 26, name: "John Stockton", pos: "PG", tier: "Legend", attributes: { inside_scoring: 75, mid_range: 85, three_point: 82, playmaking: 99, perimeter_defense: 94, interior_defense: 40, rebounding: 50, athleticism: 80, basketball_iq: 97 }, career_stats: { usg_pct: 18.0, fg_pct: 51.5, ppg: 13.1, rpg: 2.7, apg: 10.5 }, shot_tendencies: { inside: 40, mid: 40, three: 20 }, target_minutes: 34, traits: ["Floor General", "Lockdown Defender"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id26.webp`, chronicle_img_url: `${chronicleBaseUrl}id26.webp`, era: "Modern Era (1990s-2000s)" },
    "allen_iverson": { id: 27, name: "Allen Iverson", pos: "SG", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 88, three_point: 78, playmaking: 88, perimeter_defense: 88, interior_defense: 45, rebounding: 60, athleticism: 98, basketball_iq: 85 }, career_stats: { usg_pct: 31.8, fg_pct: 42.5, ppg: 26.7, rpg: 3.7, apg: 6.2 }, shot_tendencies: { inside: 50, mid: 35, three: 15 }, target_minutes: 38, traits: ["Ankle Breaker", "Unstoppable Scorer", "Tireless Motor"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id27.webp`, chronicle_img_url: `${chronicleBaseUrl}id27.webp`, era: "Modern Era (1990s-2000s)" },
    "isiah_thomas": { id: 28, name: "Isiah Thomas", pos: "PG", tier: "Legend", attributes: { inside_scoring: 88, mid_range: 86, three_point: 70, playmaking: 95, perimeter_defense: 88, interior_defense: 45, rebounding: 60, athleticism: 91, basketball_iq: 92 }, career_stats: { usg_pct: 26.2, fg_pct: 45.2, ppg: 19.2, rpg: 3.6, apg: 9.3 }, shot_tendencies: { inside: 50, mid: 40, three: 10 }, target_minutes: 36, traits: ["Ankle Breaker", "Floor General"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id28.webp`, chronicle_img_url: `${chronicleBaseUrl}id28.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "kawhi_leonard": { id: 29, name: "Kawhi Leonard", pos: "SF", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 95, three_point: 85, playmaking: 80, perimeter_defense: 100, interior_defense: 75, rebounding: 80, athleticism: 92, basketball_iq: 94 }, career_stats: { usg_pct: 27.0, fg_pct: 49.3, ppg: 19.2, rpg: 6.4, apg: 2.9 }, shot_tendencies: { inside: 30, mid: 50, three: 20 }, target_minutes: 34, traits: ["Lockdown Defender", "Clutch Performer", "Alpha Dog"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id29.webp`, chronicle_img_url: `${chronicleBaseUrl}id29.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "patrick_ewing": { id: 30, name: "Patrick Ewing", pos: "C", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 88, three_point: 20, playmaking: 60, perimeter_defense: 50, interior_defense: 94, rebounding: 91, athleticism: 86, basketball_iq: 84 }, career_stats: { usg_pct: 29.0, fg_pct: 50.4, ppg: 21.0, rpg: 9.8, apg: 1.9 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 35, traits: ["Rim Protector", "Unstoppable Scorer"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id30.webp`, chronicle_img_url: `${chronicleBaseUrl}id30.webp`, era: "Modern Era (1990s-2000s)" },
    "david_robinson": { id: 31, name: "David Robinson", pos: "C", tier: "Legend", attributes: { inside_scoring: 93, mid_range: 84, three_point: 50, playmaking: 70, perimeter_defense: 70, interior_defense: 95, rebounding: 92, athleticism: 95, basketball_iq: 91 }, career_stats: { usg_pct: 28.5, fg_pct: 51.8, ppg: 21.1, rpg: 10.6, apg: 2.5 }, shot_tendencies: { inside: 65, mid: 30, three: 5 }, target_minutes: 34, traits: ["Rim Protector", "Transition Threat"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id31.webp`, chronicle_img_url: `${chronicleBaseUrl}id31.webp`, era: "Modern Era (1990s-2000s)" },
    "clyde_drexler": { id: 32, name: "Clyde Drexler", pos: "SG", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 80, three_point: 78, playmaking: 85, perimeter_defense: 84, interior_defense: 60, rebounding: 78, athleticism: 94, basketball_iq: 88 }, career_stats: { usg_pct: 26.1, fg_pct: 47.2, ppg: 20.4, rpg: 6.1, apg: 5.6 }, shot_tendencies: { inside: 50, mid: 30, three: 20 }, target_minutes: 34, traits: ["Transition Threat", "Ankle Breaker"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id32.webp`, chronicle_img_url: `${chronicleBaseUrl}id32.webp`, era: "Modern Era (1990s-2000s)" },
    "george_gervin": { id: 33, name: "George Gervin", pos: "SG", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 96, three_point: 60, playmaking: 70, perimeter_defense: 70, interior_defense: 50, rebounding: 65, athleticism: 87, basketball_iq: 85 }, career_stats: { usg_pct: 32.8, fg_pct: 51.1, ppg: 26.2, rpg: 4.6, apg: 2.8 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 33, traits: ["Unstoppable Scorer", "Heat Check"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id33.webp`, chronicle_img_url: `${chronicleBaseUrl}id33.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "john_havlicek": { id: 34, name: "John Havlicek", pos: "SF", tier: "Legend", attributes: { inside_scoring: 86, mid_range: 88, three_point: 50, playmaking: 85, perimeter_defense: 90, interior_defense: 65, rebounding: 78, athleticism: 88, basketball_iq: 93 }, career_stats: { usg_pct: 25.0, fg_pct: 43.9, ppg: 20.8, rpg: 6.3, apg: 4.8 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 36, traits: ["Tireless Motor", "Clutch Performer"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id34.webp`, chronicle_img_url: `${chronicleBaseUrl}id34.webp`, era: "Pioneers Era (1940s-1960s)" },
    "rick_barry": { id: 35, name: "Rick Barry", pos: "SF", tier: "Legend", attributes: { inside_scoring: 84, mid_range: 90, three_point: 80, playmaking: 86, perimeter_defense: 82, interior_defense: 60, rebounding: 75, athleticism: 84, basketball_iq: 90 }, career_stats: { usg_pct: 27.5, fg_pct: 44.9, ppg: 24.8, rpg: 6.7, apg: 4.9 }, shot_tendencies: { inside: 40, mid: 40, three: 20 }, target_minutes: 35, traits: ["Unstoppable Scorer", "Floor General"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id35.webp`, chronicle_img_url: `${chronicleBaseUrl}id35.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "bob_pettit": { id: 36, name: "Bob Pettit", pos: "PF", tier: "Legend", attributes: { inside_scoring: 92, mid_range: 85, three_point: 30, playmaking: 70, perimeter_defense: 70, interior_defense: 75, rebounding: 96, athleticism: 85, basketball_iq: 88 }, career_stats: { usg_pct: 28.0, fg_pct: 43.6, ppg: 26.4, rpg: 16.2, apg: 3.0 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 36, traits: ["Tireless Motor", "Post Anchor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id36.webp`, chronicle_img_url: `${chronicleBaseUrl}id36.webp`, era: "Pioneers Era (1940s-1960s)" },
    "dominique_wilkins": { id: 37, name: "Dominique Wilkins", pos: "SF", tier: "Legend", attributes: { inside_scoring: 95, mid_range: 88, three_point: 72, playmaking: 70, perimeter_defense: 70, interior_defense: 60, rebounding: 78, athleticism: 98, basketball_iq: 82 }, career_stats: { usg_pct: 30.3, fg_pct: 46.1, ppg: 24.8, rpg: 6.7, apg: 2.5 }, shot_tendencies: { inside: 60, mid: 30, three: 10 }, target_minutes: 35, traits: ["Transition Threat", "Unstoppable Scorer"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id37.webp`, chronicle_img_url: `${chronicleBaseUrl}id37.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    
    // All-Star Tier
    "chris_paul": { id: 38, name: "Chris Paul", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 80, mid_range: 90, three_point: 84, playmaking: 98, perimeter_defense: 92, interior_defense: 40, rebounding: 60, athleticism: 86, basketball_iq: 98 }, career_stats: { usg_pct: 24.0, fg_pct: 47.2, ppg: 17.9, rpg: 4.5, apg: 9.5 }, shot_tendencies: { inside: 30, mid: 50, three: 20 }, target_minutes: 33, traits: ["Floor General", "Clutch Performer"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id38.webp`, chronicle_img_url: `${chronicleBaseUrl}id38.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "james_harden": { id: 39, name: "James Harden", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 92, mid_range: 80, three_point: 90, playmaking: 94, perimeter_defense: 78, interior_defense: 60, rebounding: 75, athleticism: 88, basketball_iq: 91 }, career_stats: { usg_pct: 30.0, fg_pct: 44.2, ppg: 24.3, rpg: 5.6, apg: 6.8 }, shot_tendencies: { inside: 40, mid: 15, three: 45 }, target_minutes: 36, traits: ["Unstoppable Scorer", "Ankle Breaker", "Floor General"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id39.webp`, chronicle_img_url: `${chronicleBaseUrl}id39.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "russell_westbrook": { id: 40, name: "Russell Westbrook", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 92, mid_range: 78, three_point: 75, playmaking: 93, perimeter_defense: 84, interior_defense: 55, rebounding: 85, athleticism: 99, basketball_iq: 86 }, career_stats: { usg_pct: 32.5, fg_pct: 43.7, ppg: 22.4, rpg: 7.3, apg: 8.4 }, shot_tendencies: { inside: 55, mid: 25, three: 20 }, target_minutes: 35, traits: ["Transition Threat", "Tireless Motor", "Ankle Breaker"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id40.webp`, chronicle_img_url: `${chronicleBaseUrl}id40.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "gary_payton": { id: 41, name: "Gary Payton", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 82, mid_range: 86, three_point: 75, playmaking: 90, perimeter_defense: 99, interior_defense: 50, rebounding: 65, athleticism: 88, basketball_iq: 92 }, career_stats: { usg_pct: 25.0, fg_pct: 46.6, ppg: 16.3, rpg: 3.9, apg: 6.7 }, shot_tendencies: { inside: 45, mid: 40, three: 15 }, target_minutes: 36, traits: ["Lockdown Defender", "Floor General"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id41.webp`, chronicle_img_url: `${chronicleBaseUrl}id41.webp`, era: "Modern Era (1990s-2000s)" },
    "jason_kidd": { id: 42, name: "Jason Kidd", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 78, mid_range: 75, three_point: 80, playmaking: 97, perimeter_defense: 93, interior_defense: 50, rebounding: 78, athleticism: 85, basketball_iq: 96 }, career_stats: { usg_pct: 19.0, fg_pct: 40.0, ppg: 12.6, rpg: 6.3, apg: 8.7 }, shot_tendencies: { inside: 40, mid: 25, three: 35 }, target_minutes: 36, traits: ["Floor General", "Lockdown Defender", "Transition Threat"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id42.webp`, chronicle_img_url: `${chronicleBaseUrl}id42.webp`, era: "Modern Era (1990s-2000s)" },
    "steve_nash": { id: 43, name: "Steve Nash", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 75, mid_range: 88, three_point: 91, playmaking: 98, perimeter_defense: 65, interior_defense: 30, rebounding: 50, athleticism: 84, basketball_iq: 97 }, career_stats: { usg_pct: 20.0, fg_pct: 49.0, ppg: 14.3, rpg: 3.0, apg: 8.5 }, shot_tendencies: { inside: 25, mid: 40, three: 35 }, target_minutes: 32, traits: ["Floor General", "Heat Check"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id43.webp`, chronicle_img_url: `${chronicleBaseUrl}id43.webp`, era: "Modern Era (1990s-2000s)" },
    "ray_allen": { id: 44, name: "Ray Allen", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 82, mid_range: 90, three_point: 98, playmaking: 80, perimeter_defense: 80, interior_defense: 40, rebounding: 60, athleticism: 86, basketball_iq: 90 }, career_stats: { usg_pct: 24.0, fg_pct: 45.2, ppg: 18.9, rpg: 4.1, apg: 3.4 }, shot_tendencies: { inside: 20, mid: 40, three: 40 }, target_minutes: 34, traits: ["Heat Check", "Clutch Performer", "Tireless Motor"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id44.webp`, chronicle_img_url: `${chronicleBaseUrl}id44.webp`, era: "Modern Era (1990s-2000s)" },
    "reggie_miller": { id: 45, name: "Reggie Miller", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 75, mid_range: 88, three_point: 97, playmaking: 75, perimeter_defense: 78, interior_defense: 35, rebounding: 50, athleticism: 84, basketball_iq: 91 }, career_stats: { usg_pct: 22.0, fg_pct: 47.1, ppg: 18.2, rpg: 3.0, apg: 3.0 }, shot_tendencies: { inside: 15, mid: 40, three: 45 }, target_minutes: 34, traits: ["Clutch Performer", "Heat Check", "Alpha Dog"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id45.webp`, chronicle_img_url: `${chronicleBaseUrl}id45.webp`, era: "Modern Era (1990s-2000s)" },
    "paul_pierce": { id: 46, name: "Paul Pierce", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 88, mid_range: 90, three_point: 85, playmaking: 82, perimeter_defense: 80, interior_defense: 60, rebounding: 75, athleticism: 82, basketball_iq: 92 }, career_stats: { usg_pct: 26.5, fg_pct: 44.5, ppg: 19.7, rpg: 5.6, apg: 3.5 }, shot_tendencies: { inside: 35, mid: 40, three: 25 }, target_minutes: 34, traits: ["Clutch Performer", "Unstoppable Scorer"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id46.webp`, chronicle_img_url: `${chronicleBaseUrl}id46.webp`, era: "Modern Era (1990s-2000s)" },
    "carmelo_anthony": { id: 47, name: "Carmelo Anthony", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 89, mid_range: 95, three_point: 84, playmaking: 75, perimeter_defense: 68, interior_defense: 62, rebounding: 78, athleticism: 84, basketball_iq: 85 }, career_stats: { usg_pct: 29.0, fg_pct: 44.7, ppg: 22.5, rpg: 6.2, apg: 2.7 }, shot_tendencies: { inside: 30, mid: 45, three: 25 }, target_minutes: 35, traits: ["Unstoppable Scorer", "Clutch Performer"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id47.webp`, chronicle_img_url: `${chronicleBaseUrl}id47.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "anthony_davis": { id: 48, name: "Anthony Davis", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 94, mid_range: 86, three_point: 78, playmaking: 72, perimeter_defense: 88, interior_defense: 95, rebounding: 91, athleticism: 91, basketball_iq: 88 }, career_stats: { usg_pct: 27.5, fg_pct: 51.5, ppg: 24.0, rpg: 10.2, apg: 2.3 }, shot_tendencies: { inside: 55, mid: 30, three: 15 }, target_minutes: 35, traits: ["Rim Protector", "Unstoppable Scorer", "Transition Threat"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id48.webp`, chronicle_img_url: `${chronicleBaseUrl}id48.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "damian_lillard": { id: 49, name: "Damian Lillard", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 86, mid_range: 88, three_point: 94, playmaking: 90, perimeter_defense: 75, interior_defense: 40, rebounding: 60, athleticism: 89, basketball_iq: 92 }, career_stats: { usg_pct: 28.5, fg_pct: 43.9, ppg: 25.2, rpg: 4.2, apg: 6.7 }, shot_tendencies: { inside: 30, mid: 25, three: 45 }, target_minutes: 36, traits: ["Clutch Performer", "Heat Check", "Alpha Dog"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id49.webp`, chronicle_img_url: `${chronicleBaseUrl}id49.webp`, era: "Hyper-Modern Era (2010s-2020s)" },
    "dennis_rodman": { id: 50, name: "Dennis Rodman", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 60, mid_range: 40, three_point: 20, playmaking: 60, perimeter_defense: 92, interior_defense: 90, rebounding: 100, athleticism: 88, basketball_iq: 85 }, career_stats: { usg_pct: 8.0, fg_pct: 52.1, ppg: 7.3, rpg: 13.1, apg: 1.8 }, shot_tendencies: { inside: 90, mid: 10, three: 0 }, target_minutes: 30, traits: ["Lockdown Defender", "Tireless Motor", "Post Anchor"], foul_tendency: 8, img_url: `${playerImgBaseUrl}id50.webp`, chronicle_img_url: `${chronicleBaseUrl}id50.webp`, era: "Modern Era (1990s-2000s)" },
    "walt_frazier": { id: 51, name: "Walt Frazier", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 80, mid_range: 88, three_point: 40, playmaking: 88, perimeter_defense: 97, interior_defense: 50, rebounding: 70, athleticism: 86, basketball_iq: 91 }, career_stats: { usg_pct: 24.0, fg_pct: 49.0, ppg: 18.9, rpg: 5.9, apg: 6.1 }, shot_tendencies: { inside: 40, mid: 60, three: 0 }, target_minutes: 34, traits: ["Lockdown Defender", "Floor General"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id51.webp`, chronicle_img_url: `${chronicleBaseUrl}id51.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "kevin_mchale": { id: 52, name: "Kevin McHale", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 96, mid_range: 75, three_point: 30, playmaking: 65, perimeter_defense: 60, interior_defense: 90, rebounding: 85, athleticism: 80, basketball_iq: 89 }, career_stats: { usg_pct: 24.1, fg_pct: 55.4, ppg: 17.9, rpg: 7.3, apg: 1.7 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 31, traits: ["Post Anchor", "Unstoppable Scorer"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id52.webp`, chronicle_img_url: `${chronicleBaseUrl}id52.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "elvin_hayes": { id: 53, name: "Elvin Hayes", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 90, mid_range: 87, three_point: 20, playmaking: 60, perimeter_defense: 60, interior_defense: 85, rebounding: 94, athleticism: 84, basketball_iq: 82 }, career_stats: { usg_pct: 27.2, fg_pct: 45.2, ppg: 21.0, rpg: 12.5, apg: 1.8 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 34, traits: ["Unstoppable Scorer", "Rim Protector"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id53.webp`, chronicle_img_url: `${chronicleBaseUrl}id53.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "robert_parish": { id: 54, name: "Robert Parish", pos: "C", tier: "All-Star", attributes: { inside_scoring: 88, mid_range: 84, three_point: 10, playmaking: 60, perimeter_defense: 50, interior_defense: 89, rebounding: 88, athleticism: 78, basketball_iq: 85 }, career_stats: { usg_pct: 19.8, fg_pct: 53.7, ppg: 14.5, rpg: 9.1, apg: 1.4 }, shot_tendencies: { inside: 65, mid: 35, three: 0 }, target_minutes: 28, traits: ["Rim Protector", "Post Anchor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id54.webp`, chronicle_img_url: `${chronicleBaseUrl}id54.webp`, era: "Modern Era (1990s-2000s)" },
    "james_worthy": { id: 55, name: "James Worthy", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 92, mid_range: 85, three_point: 50, playmaking: 75, perimeter_defense: 75, interior_defense: 60, rebounding: 70, athleticism: 90, basketball_iq: 86 }, career_stats: { usg_pct: 22.5, fg_pct: 52.1, ppg: 17.6, rpg: 5.1, apg: 3.0 }, shot_tendencies: { inside: 60, mid: 35, three: 5 }, target_minutes: 32, traits: ["Transition Threat", "Clutch Performer"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id55.webp`, chronicle_img_url: `${chronicleBaseUrl}id55.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "bob_cousy": { id: 56, name: "Bob Cousy", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 78, mid_range: 80, three_point: 30, playmaking: 97, perimeter_defense: 75, interior_defense: 40, rebounding: 60, athleticism: 82, basketball_iq: 94 }, career_stats: { usg_pct: 26.0, fg_pct: 37.5, ppg: 18.4, rpg: 5.2, apg: 7.5 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 32, traits: ["Floor General", "Ankle Breaker"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id56.webp`, chronicle_img_url: `${chronicleBaseUrl}id56.webp`, era: "Pioneers Era (1940s-1960s)" },
    "nate_archibald": { id: 57, name: "Nate Archibald", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 88, mid_range: 82, three_point: 50, playmaking: 94, perimeter_defense: 80, interior_defense: 40, rebounding: 50, athleticism: 90, basketball_iq: 88 }, career_stats: { usg_pct: 25.0, fg_pct: 46.7, ppg: 18.8, rpg: 2.3, apg: 7.4 }, shot_tendencies: { inside: 60, mid: 35, three: 5 }, target_minutes: 33, traits: ["Floor General", "Ankle Breaker"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id57.webp`, chronicle_img_url: `${chronicleBaseUrl}id57.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "bill_walton": { id: 58, name: "Bill Walton", pos: "C", tier: "All-Star", attributes: { inside_scoring: 85, mid_range: 75, three_point: 20, playmaking: 88, perimeter_defense: 65, interior_defense: 92, rebounding: 93, athleticism: 82, basketball_iq: 95 }, career_stats: { usg_pct: 20.0, fg_pct: 52.1, ppg: 13.3, rpg: 10.5, apg: 3.4 }, shot_tendencies: { inside: 70, mid: 30, three: 0 }, target_minutes: 30, traits: ["Floor General", "Rim Protector"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id58.webp`, chronicle_img_url: `${chronicleBaseUrl}id58.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "pete_maravich": { id: 59, name: "Pete Maravich", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 85, mid_range: 88, three_point: 75, playmaking: 92, perimeter_defense: 70, interior_defense: 40, rebounding: 60, athleticism: 85, basketball_iq: 89 }, career_stats: { usg_pct: 30.5, fg_pct: 44.1, ppg: 24.2, rpg: 4.2, apg: 5.4 }, shot_tendencies: { inside: 40, mid: 40, three: 20 }, target_minutes: 34, traits: ["Ankle Breaker", "Heat Check"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id59.webp`, chronicle_img_url: `${chronicleBaseUrl}id59.webp`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "george_mikan": { id: 60, name: "George Mikan", pos: "C", tier: "All-Star", attributes: { inside_scoring: 95, mid_range: 70, three_point: 5, playmaking: 65, perimeter_defense: 40, interior_defense: 88, rebounding: 90, athleticism: 70, basketball_iq: 85 }, career_stats: { usg_pct: 30.0, fg_pct: 40.4, ppg: 23.1, rpg: 13.4, apg: 2.8 }, shot_tendencies: { inside: 90, mid: 10, three: 0 }, target_minutes: 34, traits: ["Post Anchor", "Rim Protector"], foul_tendency: 9, img_url: `${playerImgBaseUrl}id60.webp`, chronicle_img_url: `${chronicleBaseUrl}id60.webp`, era: "Pioneers Era (1940s-1960s)" }
};

export const historicalPlayers: { [key: string]: Player } = {
    // 1990s Bulls (First 3-Peat)
    "john_paxson": { id: 61, name: "John Paxson", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 70, mid_range: 92, three_point: 80, playmaking: 80, perimeter_defense: 80, interior_defense: 30, rebounding: 40, athleticism: 75, basketball_iq: 88 }, career_stats: { usg_pct: 14.0, fg_pct: 49.9, ppg: 7.6, rpg: 1.2, apg: 3.6 }, shot_tendencies: { inside: 20, mid: 60, three: 20 }, target_minutes: 30, traits: ["Clutch Performer"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id61.webp`, era: "Modern Era (1990s-2000s)" },
    "horace_grant": { id: 62, name: "Horace Grant", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 84, mid_range: 72, three_point: 10, playmaking: 70, perimeter_defense: 85, interior_defense: 88, rebounding: 90, athleticism: 85, basketball_iq: 86 }, career_stats: { usg_pct: 18.0, fg_pct: 50.9, ppg: 11.2, rpg: 8.1, apg: 2.2 }, shot_tendencies: { inside: 70, mid: 30, three: 0 }, target_minutes: 36, traits: ["Tireless Motor", "Lockdown Defender"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id62.webp`, era: "Modern Era (1990s-2000s)" },
    "bill_cartwright": { id: 63, name: "Bill Cartwright", pos: "C", tier: "All-Star", attributes: { inside_scoring: 82, mid_range: 70, three_point: 5, playmaking: 60, perimeter_defense: 40, interior_defense: 85, rebounding: 82, athleticism: 65, basketball_iq: 84 }, career_stats: { usg_pct: 20.0, fg_pct: 46.9, ppg: 13.2, rpg: 6.3, apg: 1.4 }, shot_tendencies: { inside: 75, mid: 25, three: 0 }, target_minutes: 30, traits: ["Post Anchor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id63.webp`, era: "Modern Era (1990s-2000s)" },
    "bj_armstrong": { id: 64, name: "B.J. Armstrong", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 75, mid_range: 88, three_point: 85, playmaking: 84, perimeter_defense: 76, interior_defense: 30, rebounding: 45, athleticism: 82, basketball_iq: 88 }, career_stats: { usg_pct: 17.0, fg_pct: 45.0, ppg: 9.8, rpg: 1.8, apg: 3.3 }, shot_tendencies: { inside: 30, mid: 40, three: 30 }, target_minutes: 25, traits: ["Floor General"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id64.webp`, era: "Modern Era (1990s-2000s)" },

    // 1990s Trail Blazers
    "terry_porter": { id: 68, name: "Terry Porter", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 80, mid_range: 84, three_point: 82, playmaking: 90, perimeter_defense: 84, interior_defense: 40, rebounding: 55, athleticism: 85, basketball_iq: 91 }, career_stats: { usg_pct: 20.0, fg_pct: 46.3, ppg: 12.2, rpg: 3.5, apg: 5.6 }, shot_tendencies: { inside: 30, mid: 40, three: 30 }, target_minutes: 35, traits: ["Floor General", "Clutch Performer"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id68.webp`, era: "Modern Era (1990s-2000s)" },
    "jerome_kersey": { id: 69, name: "Jerome Kersey", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 85, mid_range: 75, three_point: 40, playmaking: 70, perimeter_defense: 82, interior_defense: 65, rebounding: 85, athleticism: 90, basketball_iq: 82 }, career_stats: { usg_pct: 18.0, fg_pct: 46.5, ppg: 10.3, rpg: 5.5, apg: 2.1 }, shot_tendencies: { inside: 70, mid: 25, three: 5 }, target_minutes: 32, traits: ["Transition Threat", "Tireless Motor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id69.webp`, era: "Modern Era (1990s-2000s)" },
    "buck_williams": { id: 70, name: "Buck Williams", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 85, mid_range: 70, three_point: 10, playmaking: 60, perimeter_defense: 70, interior_defense: 86, rebounding: 95, athleticism: 82, basketball_iq: 85 }, career_stats: { usg_pct: 16.0, fg_pct: 54.9, ppg: 12.8, rpg: 10.0, apg: 1.3 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 33, traits: ["Post Anchor", "Tireless Motor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id70.webp`, era: "Modern Era (1990s-2000s)" },
    
    // 1990s Suns
    "kevin_johnson": { id: 71, name: "Kevin Johnson", pos: "PG", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 84, three_point: 65, playmaking: 95, perimeter_defense: 82, interior_defense: 40, rebounding: 58, athleticism: 96, basketball_iq: 90 }, career_stats: { usg_pct: 25.0, fg_pct: 49.3, ppg: 17.9, rpg: 3.3, apg: 9.1 }, shot_tendencies: { inside: 60, mid: 35, three: 5 }, target_minutes: 36, traits: ["Ankle Breaker", "Transition Threat"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id71.webp`, era: "Modern Era (1990s-2000s)" },
    "dan_majerle": { id: 72, name: "Dan Majerle", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 80, mid_range: 82, three_point: 88, playmaking: 80, perimeter_defense: 88, interior_defense: 60, rebounding: 70, athleticism: 88, basketball_iq: 86 }, career_stats: { usg_pct: 20.0, fg_pct: 43.1, ppg: 11.4, rpg: 4.5, apg: 2.9 }, shot_tendencies: { inside: 30, mid: 30, three: 40 }, target_minutes: 35, traits: ["Heat Check", "Lockdown Defender"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id72.webp`, era: "Modern Era (1990s-2000s)" },
    "tom_chambers": { id: 73, name: "Tom Chambers", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 90, mid_range: 86, three_point: 75, playmaking: 70, perimeter_defense: 65, interior_defense: 60, rebounding: 80, athleticism: 86, basketball_iq: 83 }, career_stats: { usg_pct: 26.0, fg_pct: 46.8, ppg: 18.1, rpg: 6.1, apg: 2.1 }, shot_tendencies: { inside: 45, mid: 40, three: 15 }, target_minutes: 32, traits: ["Unstoppable Scorer", "Transition Threat"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id73.webp`, era: "Modern Era (1990s-2000s)" },
    
    // Additional Historical Players (1991-1993 Series)
    "scott_williams": { id: 74, name: "Scott Williams", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 78, mid_range: 60, three_point: 10, playmaking: 55, perimeter_defense: 70, interior_defense: 82, rebounding: 85, athleticism: 80, basketball_iq: 75 }, career_stats: { usg_pct: 15.0, fg_pct: 47.0, ppg: 5.1, rpg: 5.3, apg: 0.7 }, shot_tendencies: { inside: 85, mid: 15, three: 0 }, target_minutes: 18, traits: ["Tireless Motor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id74.webp`, era: "Modern Era (1990s-2000s)" },
    "cliff_levingston": { id: 75, name: "Cliff Levingston", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 80, mid_range: 65, three_point: 10, playmaking: 60, perimeter_defense: 75, interior_defense: 78, rebounding: 83, athleticism: 82, basketball_iq: 78 }, career_stats: { usg_pct: 16.0, fg_pct: 50.1, ppg: 7.1, rpg: 5.7, apg: 1.0 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 20, traits: ["Post Anchor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id75.webp`, era: "Modern Era (1990s-2000s)" },
    "will_perdue": { id: 76, name: "Will Perdue", pos: "C", tier: "Role Player", attributes: { inside_scoring: 75, mid_range: 70, three_point: 5, playmaking: 50, perimeter_defense: 40, interior_defense: 75, rebounding: 80, athleticism: 60, basketball_iq: 70 }, career_stats: { usg_pct: 14.0, fg_pct: 50.5, ppg: 4.7, rpg: 4.9, apg: 0.6 }, shot_tendencies: { inside: 70, mid: 30, three: 0 }, target_minutes: 15, traits: ["Post Anchor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id76.webp`, era: "Modern Era (1990s-2000s)" },
    "craig_hodges": { id: 78, name: "Craig Hodges", pos: "SG", tier: "Role Player", attributes: { inside_scoring: 60, mid_range: 80, three_point: 95, playmaking: 70, perimeter_defense: 70, interior_defense: 30, rebounding: 40, athleticism: 75, basketball_iq: 80 }, career_stats: { usg_pct: 15.0, fg_pct: 42.4, ppg: 8.5, rpg: 1.3, apg: 2.5 }, shot_tendencies: { inside: 10, mid: 30, three: 60 }, target_minutes: 16, traits: ["Heat Check"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id78.webp`, era: "Modern Era (1990s-2000s)" },
    "byron_scott": { id: 79, name: "Byron Scott", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 85, mid_range: 86, three_point: 84, playmaking: 80, perimeter_defense: 85, interior_defense: 45, rebounding: 60, athleticism: 88, basketball_iq: 86 }, career_stats: { usg_pct: 21.0, fg_pct: 48.2, ppg: 14.1, rpg: 2.8, apg: 2.5 }, shot_tendencies: { inside: 40, mid: 40, three: 20 }, target_minutes: 33, traits: ["Transition Threat"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id79.webp`, era: "Modern Era (1990s-2000s)" },
    "sam_perkins": { id: 80, name: "Sam Perkins", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 80, mid_range: 84, three_point: 75, playmaking: 70, perimeter_defense: 68, interior_defense: 78, rebounding: 82, athleticism: 75, basketball_iq: 85 }, career_stats: { usg_pct: 20.0, fg_pct: 45.9, ppg: 11.9, rpg: 6.0, apg: 1.5 }, shot_tendencies: { inside: 50, mid: 30, three: 20 }, target_minutes: 32, traits: ["Unstoppable Scorer"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id80.webp`, era: "Modern Era (1990s-2000s)" },
    "vlade_divac": { id: 81, name: "Vlade Divac", pos: "C", tier: "All-Star", attributes: { inside_scoring: 86, mid_range: 78, three_point: 45, playmaking: 85, perimeter_defense: 55, interior_defense: 80, rebounding: 88, athleticism: 78, basketball_iq: 90 }, career_stats: { usg_pct: 21.0, fg_pct: 49.5, ppg: 11.8, rpg: 8.2, apg: 3.1 }, shot_tendencies: { inside: 60, mid: 35, three: 5 }, target_minutes: 34, traits: ["Floor General"], foul_tendency: 8, img_url: `${playerImgBaseUrl}id81.webp`, era: "Modern Era (1990s-2000s)" },
    "ac_green": { id: 82, name: "A.C. Green", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 82, mid_range: 75, three_point: 30, playmaking: 60, perimeter_defense: 80, interior_defense: 84, rebounding: 90, athleticism: 80, basketball_iq: 82 }, career_stats: { usg_pct: 15.0, fg_pct: 49.4, ppg: 9.6, rpg: 7.4, apg: 1.1 }, shot_tendencies: { inside: 75, mid: 25, three: 0 }, target_minutes: 28, traits: ["Tireless Motor"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id82.webp`, era: "Modern Era (1990s-2000s)" },
    "mychal_thompson": { id: 84, name: "Mychal Thompson", pos: "C", tier: "Role Player", attributes: { inside_scoring: 84, mid_range: 80, three_point: 10, playmaking: 65, perimeter_defense: 60, interior_defense: 78, rebounding: 82, athleticism: 76, basketball_iq: 80 }, career_stats: { usg_pct: 18.0, fg_pct: 50.4, ppg: 13.7, rpg: 7.4, apg: 2.3 }, shot_tendencies: { inside: 70, mid: 30, three: 0 }, target_minutes: 18, traits: ["Post Anchor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id84.webp`, era: "Modern Era (1990s-2000s)" },
    "elden_campbell": { id: 85, name: "Elden Campbell", pos: "C", tier: "Role Player", attributes: { inside_scoring: 86, mid_range: 65, three_point: 10, playmaking: 55, perimeter_defense: 60, interior_defense: 85, rebounding: 84, athleticism: 83, basketball_iq: 74 }, career_stats: { usg_pct: 19.0, fg_pct: 45.8, ppg: 10.3, rpg: 5.9, apg: 1.1 }, shot_tendencies: { inside: 90, mid: 10, three: 0 }, target_minutes: 20, traits: ["Rim Protector"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id85.webp`, era: "Modern Era (1990s-2000s)" },
    "kevin_duckworth": { id: 86, name: "Kevin Duckworth", pos: "C", tier: "All-Star", attributes: { inside_scoring: 83, mid_range: 68, three_point: 5, playmaking: 60, perimeter_defense: 40, interior_defense: 76, rebounding: 85, athleticism: 68, basketball_iq: 78 }, career_stats: { usg_pct: 22.0, fg_pct: 45.7, ppg: 11.8, rpg: 5.8, apg: 0.9 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 30, traits: ["Post Anchor"], foul_tendency: 8, img_url: `${playerImgBaseUrl}id86.webp`, era: "Modern Era (1990s-2000s)" },
    "danny_ainge": { id: 87, name: "Danny Ainge", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 78, mid_range: 85, three_point: 89, playmaking: 82, perimeter_defense: 86, interior_defense: 50, rebounding: 55, athleticism: 80, basketball_iq: 90 }, career_stats: { usg_pct: 18.0, fg_pct: 46.9, ppg: 11.5, rpg: 2.7, apg: 4.0 }, shot_tendencies: { inside: 30, mid: 35, three: 35 }, target_minutes: 26, traits: ["Heat Check", "Clutch Performer"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id87.webp`, era: "Modern Era (1990s-2000s)" },
    "cliff_robinson": { id: 88, name: "Cliff Robinson", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 86, mid_range: 84, three_point: 80, playmaking: 75, perimeter_defense: 84, interior_defense: 80, rebounding: 78, athleticism: 87, basketball_iq: 83 }, career_stats: { usg_pct: 21.0, fg_pct: 43.8, ppg: 14.2, rpg: 4.6, apg: 2.2 }, shot_tendencies: { inside: 45, mid: 30, three: 25 }, target_minutes: 28, traits: ["Unstoppable Scorer", "Tireless Motor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id88.webp`, era: "Modern Era (1990s-2000s)" },
    "mark_bryant": { id: 89, name: "Mark Bryant", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 80, mid_range: 60, three_point: 5, playmaking: 50, perimeter_defense: 60, interior_defense: 74, rebounding: 82, athleticism: 75, basketball_iq: 70 }, career_stats: { usg_pct: 14.0, fg_pct: 50.1, ppg: 5.4, rpg: 3.8, apg: 0.5 }, shot_tendencies: { inside: 90, mid: 10, three: 0 }, target_minutes: 15, traits: ["Post Anchor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id89.webp`, era: "Modern Era (1990s-2000s)" },
    "richard_dumas": { id: 91, name: "Richard Dumas", pos: "SF", tier: "Role Player", attributes: { inside_scoring: 88, mid_range: 75, three_point: 60, playmaking: 68, perimeter_defense: 80, interior_defense: 60, rebounding: 75, athleticism: 90, basketball_iq: 70 }, career_stats: { usg_pct: 23.0, fg_pct: 52.4, ppg: 15.8, rpg: 4.6, apg: 1.8 }, shot_tendencies: { inside: 65, mid: 30, three: 5 }, target_minutes: 25, traits: ["Transition Threat"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id91.webp`, era: "Modern Era (1990s-2000s)" },
    "mark_west": { id: 92, name: "Mark West", pos: "C", tier: "Role Player", attributes: { inside_scoring: 82, mid_range: 50, three_point: 5, playmaking: 50, perimeter_defense: 50, interior_defense: 82, rebounding: 84, athleticism: 78, basketball_iq: 75 }, career_stats: { usg_pct: 14.0, fg_pct: 58.0, ppg: 5.7, rpg: 4.9, apg: 0.5 }, shot_tendencies: { inside: 95, mid: 5, three: 0 }, target_minutes: 22, traits: ["Rim Protector"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id92.webp`, era: "Modern Era (1990s-2000s)" },
    "cedric_ceballos": { id: 93, name: "Cedric Ceballos", pos: "SF", tier: "Role Player", attributes: { inside_scoring: 90, mid_range: 80, three_point: 70, playmaking: 65, perimeter_defense: 70, interior_defense: 55, rebounding: 80, athleticism: 85, basketball_iq: 78 }, career_stats: { usg_pct: 20.0, fg_pct: 50.0, ppg: 14.3, rpg: 5.3, apg: 1.2 }, shot_tendencies: { inside: 60, mid: 30, three: 10 }, target_minutes: 20, traits: ["Unstoppable Scorer"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id93.webp`, era: "Modern Era (1990s-2000s)" },
    "oliver_miller": { id: 94, name: "Oliver Miller", pos: "C", tier: "Role Player", attributes: { inside_scoring: 78, mid_range: 60, three_point: 20, playmaking: 70, perimeter_defense: 45, interior_defense: 78, rebounding: 83, athleticism: 65, basketball_iq: 77 }, career_stats: { usg_pct: 17.0, fg_pct: 50.4, ppg: 7.4, rpg: 5.9, apg: 2.2 }, shot_tendencies: { inside: 80, mid: 15, three: 5 }, target_minutes: 18, traits: ["Rim Protector"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id94.webp`, era: "Modern Era (1990s-2000s)" },
    "bob_hansen": { id: 96, name: "Bob Hansen", pos: "SG", tier: "Role Player", attributes: { inside_scoring: 70, mid_range: 78, three_point: 75, playmaking: 72, perimeter_defense: 82, interior_defense: 40, rebounding: 50, athleticism: 75, basketball_iq: 80 }, career_stats: { usg_pct: 12.0, fg_pct: 44.0, ppg: 5.3, rpg: 1.6, apg: 1.3 }, shot_tendencies: { inside: 30, mid: 40, three: 30 }, target_minutes: 12, traits: ["Lockdown Defender"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id96.webp`, era: "Modern Era (1990s-2000s)" },
    "tony_smith": { id: 99, name: "Tony Smith", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 78, mid_range: 75, three_point: 65, playmaking: 80, perimeter_defense: 78, interior_defense: 40, rebounding: 50, athleticism: 82, basketball_iq: 79 }, career_stats: { usg_pct: 16.0, fg_pct: 45.0, ppg: 5.2, rpg: 1.4, apg: 2.5 }, shot_tendencies: { inside: 50, mid: 35, three: 15 }, target_minutes: 14, traits: ["Floor General"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id99.webp`, era: "Modern Era (1990s-2000s)" },
    "stacey_king": { id: 100, name: "Stacey King", pos: "C", tier: "Role Player", attributes: { inside_scoring: 80, mid_range: 70, three_point: 10, playmaking: 55, perimeter_defense: 50, interior_defense: 70, rebounding: 75, athleticism: 78, basketball_iq: 70 }, career_stats: { usg_pct: 18.0, fg_pct: 46.1, ppg: 6.6, rpg: 3.3, apg: 0.7 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 15, traits: [], foul_tendency: 6, img_url: `${playerImgBaseUrl}id100.webp`, era: "Modern Era (1990s-2000s)" },
    "wayne_cooper": { id: 101, name: "Wayne Cooper", pos: "C", tier: "Role Player", attributes: { inside_scoring: 77, mid_range: 65, three_point: 5, playmaking: 50, perimeter_defense: 50, interior_defense: 80, rebounding: 84, athleticism: 70, basketball_iq: 75 }, career_stats: { usg_pct: 14.0, fg_pct: 45.8, ppg: 7.9, rpg: 6.2, apg: 0.7 }, shot_tendencies: { inside: 85, mid: 15, three: 0 }, target_minutes: 18, traits: ["Rim Protector"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id101.webp`, era: "Modern Era (1990s-2000s)" },
    "trent_tucker": { id: 105, name: "Trent Tucker", pos: "SG", tier: "Role Player", attributes: { inside_scoring: 65, mid_range: 82, three_point: 88, playmaking: 70, perimeter_defense: 75, interior_defense: 35, rebounding: 45, athleticism: 76, basketball_iq: 81 }, career_stats: { usg_pct: 15.0, fg_pct: 43.8, ppg: 8.2, rpg: 2.0, apg: 2.0 }, shot_tendencies: { inside: 20, mid: 40, three: 40 }, target_minutes: 16, traits: ["Heat Check"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id105.webp`, era: "Modern Era (1990s-2000s)" },
    "darrell_walker": { id: 106, name: "Darrell Walker", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 76, mid_range: 70, three_point: 40, playmaking: 82, perimeter_defense: 85, interior_defense: 50, rebounding: 65, athleticism: 83, basketball_iq: 84 }, career_stats: { usg_pct: 17.0, fg_pct: 43.0, ppg: 8.9, rpg: 4.6, apg: 4.4 }, shot_tendencies: { inside: 60, mid: 35, three: 5 }, target_minutes: 20, traits: ["Lockdown Defender", "Floor General"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id106.webp`, era: "Modern Era (1990s-2000s)" },
    "frank_johnson": { id: 109, name: "Frank Johnson", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 75, mid_range: 84, three_point: 70, playmaking: 83, perimeter_defense: 78, interior_defense: 40, rebounding: 50, athleticism: 79, basketball_iq: 85 }, career_stats: { usg_pct: 16.0, fg_pct: 44.9, ppg: 8.3, rpg: 1.7, apg: 5.5 }, shot_tendencies: { inside: 40, mid: 45, three: 15 }, target_minutes: 14, traits: ["Floor General"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id109.webp`, era: "Modern Era (1990s-2000s)" },
    "terry_teagle": { id: 110, name: "Terry Teagle", pos: "SG", tier: "Role Player", attributes: { inside_scoring: 84, mid_range: 78, three_point: 60, playmaking: 70, perimeter_defense: 75, interior_defense: 50, rebounding: 65, athleticism: 83, basketball_iq: 75 }, career_stats: { usg_pct: 20.0, fg_pct: 47.0, ppg: 11.6, rpg: 2.6, apg: 1.6 }, shot_tendencies: { inside: 50, mid: 45, three: 5 }, target_minutes: 15, traits: ["Transition Threat"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id110.webp`, era: "Modern Era (1990s-2000s)" },
    "larry_drew": { id: 111, name: "Larry Drew", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 72, mid_range: 80, three_point: 70, playmaking: 84, perimeter_defense: 76, interior_defense: 30, rebounding: 40, athleticism: 78, basketball_iq: 82 }, career_stats: { usg_pct: 16.0, fg_pct: 46.7, ppg: 11.4, rpg: 1.8, apg: 5.2 }, shot_tendencies: { inside: 40, mid: 45, three: 15 }, target_minutes: 12, traits: ["Floor General"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id111.webp`, era: "Modern Era (1990s-2000s)" },
    "irving_thomas": { id: 112, name: "Irving Thomas", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 75, mid_range: 60, three_point: 20, playmaking: 55, perimeter_defense: 65, interior_defense: 72, rebounding: 78, athleticism: 77, basketball_iq: 70 }, career_stats: { usg_pct: 12.0, fg_pct: 45.0, ppg: 2.0, rpg: 1.7, apg: 0.1 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 8, traits: [], foul_tendency: 5, img_url: `${playerImgBaseUrl}id112.webp`, era: "Modern Era (1990s-2000s)" },
    "ennis_whatley": { id: 113, name: "Ennis Whatley", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 76, mid_range: 75, three_point: 40, playmaking: 85, perimeter_defense: 80, interior_defense: 35, rebounding: 50, athleticism: 81, basketball_iq: 83 }, career_stats: { usg_pct: 17.0, fg_pct: 45.3, ppg: 6.4, rpg: 1.9, apg: 4.6 }, shot_tendencies: { inside: 55, mid: 40, three: 5 }, target_minutes: 14, traits: ["Floor General"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id113.webp`, era: "Modern Era (1990s-2000s)" },
    "robert_pack": { id: 114, name: "Robert Pack", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 85, mid_range: 74, three_point: 70, playmaking: 80, perimeter_defense: 78, interior_defense: 40, rebounding: 55, athleticism: 92, basketball_iq: 78 }, career_stats: { usg_pct: 22.0, fg_pct: 42.5, ppg: 9.2, rpg: 2.4, apg: 4.6 }, shot_tendencies: { inside: 60, mid: 25, three: 15 }, target_minutes: 16, traits: ["Transition Threat", "Ankle Breaker"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id114.webp`, era: "Modern Era (1990s-2000s)" },
    "negele_knight": { id: 115, name: "Negele Knight", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 78, mid_range: 76, three_point: 65, playmaking: 82, perimeter_defense: 77, interior_defense: 38, rebounding: 48, athleticism: 84, basketball_iq: 79 }, career_stats: { usg_pct: 18.0, fg_pct: 42.1, ppg: 6.2, rpg: 2.0, apg: 3.2 }, shot_tendencies: { inside: 50, mid: 35, three: 15 }, target_minutes: 15, traits: ["Floor General"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id115.webp`, era: "Modern Era (1990s-2000s)" },
    "tom_tolbert": { id: 116, name: "Tom Tolbert", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 74, mid_range: 70, three_point: 72, playmaking: 65, perimeter_defense: 68, interior_defense: 70, rebounding: 75, athleticism: 70, basketball_iq: 76 }, career_stats: { usg_pct: 14.0, fg_pct: 43.5, ppg: 4.4, rpg: 2.9, apg: 0.7 }, shot_tendencies: { inside: 50, mid: 30, three: 20 }, target_minutes: 12, traits: [], foul_tendency: 6, img_url: `${playerImgBaseUrl}id116.webp`, era: "Modern Era (1990s-2000s)" },
    "rodney_mccray": { id: 117, name: "Rodney McCray", pos: "SF", tier: "Role Player", attributes: { inside_scoring: 75, mid_range: 70, three_point: 30, playmaking: 75, perimeter_defense: 86, interior_defense: 78, rebounding: 79, athleticism: 78, basketball_iq: 84 }, career_stats: { usg_pct: 12.0, fg_pct: 45.1, ppg: 9.0, rpg: 5.3, apg: 2.6 }, shot_tendencies: { inside: 60, mid: 38, three: 2 }, target_minutes: 20, traits: ["Lockdown Defender"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id117.webp`, era: "Modern Era (1990s-2000s)" },
    "alaan_abdelnaby": { id: 118, name: "Alaan Abdelnaby", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 80, mid_range: 70, three_point: 10, playmaking: 55, perimeter_defense: 60, interior_defense: 75, rebounding: 80, athleticism: 76, basketball_iq: 72 }, career_stats: { usg_pct: 18.0, fg_pct: 50.2, ppg: 5.7, rpg: 3.3, apg: 0.3 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 13, traits: ["Post Anchor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id118.webp`, era: "Modern Era (1990s-2000s)" },

    // 1996-1998 Bulls (Second 3-Peat)
    "ron_harper": { id: 119, name: "Ron Harper", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 82, mid_range: 78, three_point: 70, playmaking: 84, perimeter_defense: 90, interior_defense: 55, rebounding: 68, athleticism: 85, basketball_iq: 88 }, career_stats: { usg_pct: 18.0, fg_pct: 46.7, ppg: 13.8, rpg: 4.3, apg: 3.9 }, shot_tendencies: { inside: 55, mid: 35, three: 10 }, target_minutes: 28, traits: ["Lockdown Defender"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id119.webp`, era: "Modern Era (1990s-2000s)" },
    "toni_kukoc": { id: 120, name: "Toni Kukoč", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 85, mid_range: 88, three_point: 85, playmaking: 92, perimeter_defense: 78, interior_defense: 65, rebounding: 75, athleticism: 80, basketball_iq: 94 }, career_stats: { usg_pct: 22.0, fg_pct: 44.7, ppg: 11.6, rpg: 4.2, apg: 3.7 }, shot_tendencies: { inside: 40, mid: 30, three: 30 }, target_minutes: 30, traits: ["Floor General", "Heat Check"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id120.webp`, era: "Modern Era (1990s-2000s)" },
    "luc_longley": { id: 121, name: "Luc Longley", pos: "C", tier: "All-Star", attributes: { inside_scoring: 84, mid_range: 75, three_point: 5, playmaking: 68, perimeter_defense: 50, interior_defense: 82, rebounding: 83, athleticism: 70, basketball_iq: 81 }, career_stats: { usg_pct: 16.0, fg_pct: 46.2, ppg: 7.2, rpg: 4.9, apg: 1.5 }, shot_tendencies: { inside: 75, mid: 25, three: 0 }, target_minutes: 28, traits: ["Post Anchor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id121.webp`, era: "Modern Era (1990s-2000s)" },
    "steve_kerr": { id: 122, name: "Steve Kerr", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 60, mid_range: 85, three_point: 99, playmaking: 75, perimeter_defense: 75, interior_defense: 30, rebounding: 40, athleticism: 70, basketball_iq: 92 }, career_stats: { usg_pct: 13.0, fg_pct: 47.9, ppg: 6.0, rpg: 1.2, apg: 1.8 }, shot_tendencies: { inside: 10, mid: 30, three: 60 }, target_minutes: 20, traits: ["Clutch Performer", "Heat Check"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id122.webp`, era: "Modern Era (1990s-2000s)" },
    "jud_buechler": { id: 123, name: "Jud Buechler", pos: "SF", tier: "Role Player", attributes: { inside_scoring: 70, mid_range: 75, three_point: 78, playmaking: 65, perimeter_defense: 78, interior_defense: 50, rebounding: 60, athleticism: 78, basketball_iq: 79 }, career_stats: { usg_pct: 10.0, fg_pct: 42.4, ppg: 3.3, rpg: 1.8, apg: 0.8 }, shot_tendencies: { inside: 40, mid: 30, three: 30 }, target_minutes: 10, traits: [], foul_tendency: 4, img_url: `${playerImgBaseUrl}id123.webp`, era: "Modern Era (1990s-2000s)" },
    "bill_wennington": { id: 124, name: "Bill Wennington", pos: "C", tier: "Role Player", attributes: { inside_scoring: 78, mid_range: 76, three_point: 10, playmaking: 55, perimeter_defense: 45, interior_defense: 74, rebounding: 78, athleticism: 65, basketball_iq: 75 }, career_stats: { usg_pct: 15.0, fg_pct: 45.8, ppg: 4.6, rpg: 2.5, apg: 0.6 }, shot_tendencies: { inside: 70, mid: 30, three: 0 }, target_minutes: 12, traits: [], foul_tendency: 6, img_url: `${playerImgBaseUrl}id124.webp`, era: "Modern Era (1990s-2000s)" },

    // 1996 Seattle SuperSonics
    "shawn_kemp": { id: 125, name: "Shawn Kemp", pos: "PF", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 72, three_point: 25, playmaking: 70, perimeter_defense: 78, interior_defense: 84, rebounding: 94, athleticism: 98, basketball_iq: 80 }, career_stats: { usg_pct: 25.0, fg_pct: 49.2, ppg: 14.6, rpg: 8.4, apg: 1.6 }, shot_tendencies: { inside: 75, mid: 25, three: 0 }, target_minutes: 36, traits: ["Transition Threat", "Post Anchor"], foul_tendency: 8, img_url: `${playerImgBaseUrl}id125.webp`, era: "Modern Era (1990s-2000s)" },
    "detlef_schrempf": { id: 126, name: "Detlef Schrempf", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 86, mid_range: 90, three_point: 86, playmaking: 85, perimeter_defense: 75, interior_defense: 65, rebounding: 82, athleticism: 78, basketball_iq: 90 }, career_stats: { usg_pct: 22.0, fg_pct: 49.1, ppg: 13.9, rpg: 6.2, apg: 3.4 }, shot_tendencies: { inside: 40, mid: 40, three: 20 }, target_minutes: 34, traits: ["Unstoppable Scorer"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id126.webp`, era: "Modern Era (1990s-2000s)" },
    "hersey_hawkins": { id: 127, name: "Hersey Hawkins", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 84, mid_range: 86, three_point: 88, playmaking: 80, perimeter_defense: 88, interior_defense: 45, rebounding: 65, athleticism: 85, basketball_iq: 87 }, career_stats: { usg_pct: 19.0, fg_pct: 46.4, ppg: 14.7, rpg: 3.6, apg: 2.9 }, shot_tendencies: { inside: 40, mid: 30, three: 30 }, target_minutes: 35, traits: ["Heat Check", "Lockdown Defender"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id127.webp`, era: "Modern Era (1990s-2000s)" },
    "nate_mcmillan": { id: 128, name: "Nate McMillan", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 70, mid_range: 75, three_point: 78, playmaking: 88, perimeter_defense: 94, interior_defense: 50, rebounding: 60, athleticism: 80, basketball_iq: 90 }, career_stats: { usg_pct: 11.0, fg_pct: 43.7, ppg: 5.9, rpg: 4.0, apg: 6.1 }, shot_tendencies: { inside: 40, mid: 30, three: 30 }, target_minutes: 24, traits: ["Floor General", "Lockdown Defender"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id128.webp`, era: "Modern Era (1990s-2000s)" },
    "frank_brickowski": { id: 129, name: "Frank Brickowski", pos: "C", tier: "Role Player", attributes: { inside_scoring: 80, mid_range: 72, three_point: 40, playmaking: 65, perimeter_defense: 55, interior_defense: 76, rebounding: 80, athleticism: 68, basketball_iq: 78 }, career_stats: { usg_pct: 18.0, fg_pct: 48.4, ppg: 10.5, rpg: 5.5, apg: 1.7 }, shot_tendencies: { inside: 70, mid: 25, three: 5 }, target_minutes: 20, traits: ["Post Anchor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id129.webp`, era: "Modern Era (1990s-2000s)" },
    "vincent_askew": { id: 130, name: "Vincent Askew", pos: "SG", tier: "Role Player", attributes: { inside_scoring: 78, mid_range: 80, three_point: 50, playmaking: 75, perimeter_defense: 82, interior_defense: 60, rebounding: 65, athleticism: 82, basketball_iq: 80 }, career_stats: { usg_pct: 17.0, fg_pct: 44.5, ppg: 6.6, rpg: 2.5, apg: 2.3 }, shot_tendencies: { inside: 50, mid: 45, three: 5 }, target_minutes: 18, traits: [], foul_tendency: 5, img_url: `${playerImgBaseUrl}id130.webp`, era: "Modern Era (1990s-2000s)" },
    "david_wingate": { id: 131, name: "David Wingate", pos: "SG", tier: "Role Player", attributes: { inside_scoring: 75, mid_range: 75, three_point: 60, playmaking: 72, perimeter_defense: 80, interior_defense: 50, rebounding: 55, athleticism: 80, basketball_iq: 78 }, career_stats: { usg_pct: 12.0, fg_pct: 46.1, ppg: 5.6, rpg: 1.8, apg: 1.8 }, shot_tendencies: { inside: 45, mid: 45, three: 10 }, target_minutes: 12, traits: [], foul_tendency: 4, img_url: `${playerImgBaseUrl}id131.webp`, era: "Modern Era (1990s-2000s)" },
    "ervin_johnson_c": { id: 132, name: "Ervin Johnson", pos: "C", tier: "Role Player", attributes: { inside_scoring: 75, mid_range: 50, three_point: 5, playmaking: 50, perimeter_defense: 50, interior_defense: 84, rebounding: 88, athleticism: 75, basketball_iq: 74 }, career_stats: { usg_pct: 9.0, fg_pct: 49.6, ppg: 4.1, rpg: 6.1, apg: 0.4 }, shot_tendencies: { inside: 95, mid: 5, three: 0 }, target_minutes: 16, traits: ["Rim Protector"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id132.webp`, era: "Modern Era (1990s-2000s)" },

    // 1997-1998 Utah Jazz
    "jeff_hornacek": { id: 133, name: "Jeff Hornacek", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 80, mid_range: 94, three_point: 90, playmaking: 86, perimeter_defense: 82, interior_defense: 40, rebounding: 55, athleticism: 78, basketball_iq: 95 }, career_stats: { usg_pct: 20.0, fg_pct: 49.6, ppg: 14.5, rpg: 3.4, apg: 4.9 }, shot_tendencies: { inside: 30, mid: 45, three: 25 }, target_minutes: 34, traits: ["Heat Check", "Floor General"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id133.webp`, era: "Modern Era (1990s-2000s)" },
    "bryon_russell": { id: 134, name: "Bryon Russell", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 82, mid_range: 80, three_point: 84, playmaking: 70, perimeter_defense: 88, interior_defense: 65, rebounding: 70, athleticism: 84, basketball_iq: 82 }, career_stats: { usg_pct: 16.0, fg_pct: 43.9, ppg: 7.9, rpg: 3.5, apg: 1.3 }, shot_tendencies: { inside: 45, mid: 25, three: 30 }, target_minutes: 32, traits: ["Lockdown Defender"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id134.webp`, era: "Modern Era (1990s-2000s)" },
    "greg_ostertag": { id: 135, name: "Greg Ostertag", pos: "C", tier: "Role Player", attributes: { inside_scoring: 76, mid_range: 40, three_point: 5, playmaking: 50, perimeter_defense: 45, interior_defense: 86, rebounding: 85, athleticism: 72, basketball_iq: 70 }, career_stats: { usg_pct: 11.0, fg_pct: 46.5, ppg: 4.6, rpg: 5.5, apg: 0.6 }, shot_tendencies: { inside: 95, mid: 5, three: 0 }, target_minutes: 24, traits: ["Rim Protector"], foul_tendency: 8, img_url: `${playerImgBaseUrl}id135.webp`, era: "Modern Era (1990s-2000s)" },
    "howard_eisley": { id: 136, name: "Howard Eisley", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 75, mid_range: 82, three_point: 80, playmaking: 84, perimeter_defense: 78, interior_defense: 35, rebounding: 45, athleticism: 80, basketball_iq: 84 }, career_stats: { usg_pct: 16.0, fg_pct: 42.9, ppg: 6.7, rpg: 1.6, apg: 3.5 }, shot_tendencies: { inside: 35, mid: 35, three: 30 }, target_minutes: 18, traits: ["Floor General"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id136.webp`, era: "Modern Era (1990s-2000s)" },
    "shandon_anderson": { id: 137, name: "Shandon Anderson", pos: "SG", tier: "Role Player", attributes: { inside_scoring: 84, mid_range: 75, three_point: 65, playmaking: 70, perimeter_defense: 80, interior_defense: 55, rebounding: 70, athleticism: 88, basketball_iq: 76 }, career_stats: { usg_pct: 15.0, fg_pct: 46.0, ppg: 7.4, rpg: 2.8, apg: 1.1 }, shot_tendencies: { inside: 60, mid: 30, three: 10 }, target_minutes: 16, traits: ["Transition Threat"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id137.webp`, era: "Modern Era (1990s-2000s)" },
    "adam_keefe": { id: 138, name: "Adam Keefe", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 80, mid_range: 65, three_point: 10, playmaking: 55, perimeter_defense: 65, interior_defense: 75, rebounding: 82, athleticism: 75, basketball_iq: 77 }, career_stats: { usg_pct: 13.0, fg_pct: 49.3, ppg: 5.0, rpg: 4.1, apg: 0.6 }, shot_tendencies: { inside: 85, mid: 15, three: 0 }, target_minutes: 15, traits: ["Tireless Motor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id138.webp`, era: "Modern Era (1990s-2000s)" },
    "greg_foster": { id: 139, name: "Greg Foster", pos: "C", tier: "Role Player", attributes: { inside_scoring: 76, mid_range: 78, three_point: 20, playmaking: 58, perimeter_defense: 50, interior_defense: 76, rebounding: 78, athleticism: 70, basketball_iq: 75 }, career_stats: { usg_pct: 14.0, fg_pct: 42.9, ppg: 3.9, rpg: 2.4, apg: 0.3 }, shot_tendencies: { inside: 70, mid: 30, three: 0 }, target_minutes: 12, traits: [], foul_tendency: 7, img_url: `${playerImgBaseUrl}id139.webp`, era: "Modern Era (1990s-2000s)" },

    // Newly added missing players
    "james_edwards": { id: 140, name: "James Edwards", pos: "C", tier: "Role Player", attributes: { inside_scoring: 82, mid_range: 70, three_point: 5, playmaking: 60, perimeter_defense: 40, interior_defense: 76, rebounding: 80, athleticism: 60, basketball_iq: 78 }, career_stats: { usg_pct: 19.0, fg_pct: 50.9, ppg: 12.7, rpg: 5.1, apg: 1.3 }, shot_tendencies: { inside: 75, mid: 25, three: 0 }, target_minutes: 14, traits: ["Post Anchor"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id140.webp`, era: "Modern Era (1990s-2000s)" },
    "randy_brown": { id: 141, name: "Randy Brown", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 76, mid_range: 70, three_point: 65, playmaking: 78, perimeter_defense: 88, interior_defense: 50, rebounding: 55, athleticism: 85, basketball_iq: 80 }, career_stats: { usg_pct: 15.0, fg_pct: 45.9, ppg: 4.8, rpg: 1.8, apg: 2.2 }, shot_tendencies: { inside: 60, mid: 30, three: 10 }, target_minutes: 15, traits: ["Lockdown Defender"], foul_tendency: 5, img_url: `${playerImgBaseUrl}id141.webp`, era: "Modern Era (1990s-2000s)" },
    "eric_snow": { id: 142, name: "Eric Snow", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 74, mid_range: 72, three_point: 40, playmaking: 84, perimeter_defense: 90, interior_defense: 55, rebounding: 60, athleticism: 80, basketball_iq: 86 }, career_stats: { usg_pct: 14.0, fg_pct: 42.6, ppg: 6.8, rpg: 2.5, apg: 5.0 }, shot_tendencies: { inside: 50, mid: 45, three: 5 }, target_minutes: 18, traits: ["Floor General", "Lockdown Defender"], foul_tendency: 4, img_url: `${playerImgBaseUrl}id142.webp`, era: "Modern Era (1990s-2000s)" },
    "sherell_ford": { id: 143, name: "Sherell Ford", pos: "SF", tier: "Role Player", attributes: { inside_scoring: 75, mid_range: 70, three_point: 60, playmaking: 65, perimeter_defense: 70, interior_defense: 60, rebounding: 70, athleticism: 78, basketball_iq: 70 }, career_stats: { usg_pct: 16.0, fg_pct: 43.1, ppg: 3.2, rpg: 1.9, apg: 0.5 }, shot_tendencies: { inside: 50, mid: 40, three: 10 }, target_minutes: 8, traits: [], foul_tendency: 5, img_url: `${playerImgBaseUrl}id143.webp`, era: "Modern Era (1990s-2000s)" },
    "jason_caffey": { id: 144, name: "Jason Caffey", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 84, mid_range: 65, three_point: 5, playmaking: 60, perimeter_defense: 65, interior_defense: 72, rebounding: 85, athleticism: 80, basketball_iq: 75 }, career_stats: { usg_pct: 17.0, fg_pct: 49.9, ppg: 7.3, rpg: 4.4, apg: 0.9 }, shot_tendencies: { inside: 85, mid: 15, three: 0 }, target_minutes: 16, traits: ["Tireless Motor"], foul_tendency: 6, img_url: `${playerImgBaseUrl}id144.webp`, era: "Modern Era (1990s-2000s)" },
    "stephen_howard": { id: 145, name: "Stephen Howard", pos: "SF", tier: "Role Player", attributes: { inside_scoring: 72, mid_range: 68, three_point: 30, playmaking: 60, perimeter_defense: 70, interior_defense: 65, rebounding: 72, athleticism: 75, basketball_iq: 72 }, career_stats: { usg_pct: 15.0, fg_pct: 47.0, ppg: 3.2, rpg: 1.8, apg: 0.3 }, shot_tendencies: { inside: 70, mid: 30, three: 0 }, target_minutes: 8, traits: [], foul_tendency: 5, img_url: `${playerImgBaseUrl}id145.webp`, era: "Modern Era (1990s-2000s)" },
    "antoine_carr": { id: 146, name: "Antoine Carr", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 86, mid_range: 82, three_point: 20, playmaking: 65, perimeter_defense: 60, interior_defense: 70, rebounding: 75, athleticism: 74, basketball_iq: 80 }, career_stats: { usg_pct: 20.0, fg_pct: 49.9, ppg: 9.3, rpg: 3.4, apg: 1.1 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 18, traits: ["Unstoppable Scorer"], foul_tendency: 7, img_url: `${playerImgBaseUrl}id146.webp`, era: "Modern Era (1990s-2000s)" },
    "chris_morris": { id: 147, name: "Chris Morris", pos: "SF", tier: "Role Player", attributes: { inside_scoring: 80, mid_range: 78, three_point: 80, playmaking: 72, perimeter_defense: 80, interior_defense: 65, rebounding: 70, athleticism: 82, basketball_iq: 79 }, career_stats: { usg_pct: 18.0, fg_pct: 42.6, ppg: 8.4, rpg: 4.0, apg: 1.5 }, shot_tendencies: { inside: 40, mid: 30, three: 30 }, target_minutes: 20, traits: [], foul_tendency: 6, img_url: `${playerImgBaseUrl}id147.webp`, era: "Modern Era (1990s-2000s)" },
    "dick_simpkins": { id: 148, name: "Dickey Simpkins", pos: "PF", tier: "Role Player", attributes: { inside_scoring: 78, mid_range: 65, three_point: 10, playmaking: 55, perimeter_defense: 60, interior_defense: 74, rebounding: 80, athleticism: 75, basketball_iq: 70 }, career_stats: { usg_pct: 16.0, fg_pct: 46.1, ppg: 4.2, rpg: 3.6, apg: 0.6 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 12, traits: [], foul_tendency: 6, img_url: `${playerImgBaseUrl}id148.webp`, era: "Modern Era (1990s-2000s)" },
    "scott_burrell": { id: 149, name: "Scott Burrell", pos: "SF", tier: "Role Player", attributes: { inside_scoring: 78, mid_range: 76, three_point: 78, playmaking: 75, perimeter_defense: 78, interior_defense: 55, rebounding: 65, athleticism: 80, basketball_iq: 82 }, career_stats: { usg_pct: 16.0, fg_pct: 42.4, ppg: 6.9, rpg: 3.5, apg: 1.4 }, shot_tendencies: { inside: 40, mid: 30, three: 30 }, target_minutes: 18, traits: [], foul_tendency: 4, img_url: `${playerImgBaseUrl}id149.webp`, era: "Modern Era (1990s-2000s)" },
    "jacque_vaughn": { id: 150, name: "Jacque Vaughn", pos: "PG", tier: "Role Player", attributes: { inside_scoring: 72, mid_range: 75, three_point: 70, playmaking: 82, perimeter_defense: 76, interior_defense: 35, rebounding: 45, athleticism: 80, basketball_iq: 84 }, career_stats: { usg_pct: 14.0, fg_pct: 41.9, ppg: 4.5, rpg: 1.3, apg: 2.5 }, shot_tendencies: { inside: 45, mid: 35, three: 20 }, target_minutes: 14, traits: ["Floor General"], foul_tendency: 3, img_url: `${playerImgBaseUrl}id150.webp`, era: "Modern Era (1990s-2000s)" }
};

export const allPlayers = { ...players, ...historicalPlayers };